options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamicSubstitutions: true

substitutions:
  # Backend Config
  _SERVICE_NAME: "novaric-backend"
  _IMAGE_NAME: "novaric-backend"
  
  # Frontend Config (NEW)
  _SERVICE_NAME_FE: "novaric-frontend"
  _IMAGE_NAME_FE: "novaric-frontend"
  
  # Shared Config
  _REGION: "europe-west1"
  _AR_REPO: "cloud-run-source-deploy"
  
  # Supabase Secrets (You must add these in Cloud Build Trigger settings)
  _SUPABASE_URL: "your-supabase-url-here" 
  _SUPABASE_KEY: "your-supabase-service-role-key-here"

steps:
  # ==========================================
  # 1. BACKEND PIPELINE
  # ==========================================
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend"
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest",
        "--cache-from", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Backend"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Backend"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--port=8080",
        "--memory=512Mi",
        "--cpu=1",
        # INJECT SUPABASE KEYS HERE
        "--set-env-vars=SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY}"
      ]

  # ==========================================
  # 2. FRONTEND PIPELINE (Parallel)
  # ==========================================
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend"
    # This assumes your frontend code is in a folder named 'frontend'
    dir: "frontend" 
    # waitFor: ['-'] means start immediately, don't wait for Backend to finish
    waitFor: ['-'] 
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:$SHORT_SHA",
        "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:latest",
        "--cache-from", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:latest",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Frontend"
    waitFor: ["Build Frontend"]
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:$SHORT_SHA"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Frontend"
    waitFor: ["Push Frontend"]
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME_FE}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:$SHORT_SHA",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--port=8080",
        "--memory=256Mi" # Frontend needs less RAM
      ]

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME_FE}:latest"